# coding: utf-8

"""
    Proxmox Datacenter Manager API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from clientapi_pdm.models.config_acme_get_config_acme_account_by_name_response_data_account_external_account_binding import ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccountExternalAccountBinding
from clientapi_pdm.models.pdm_config_acme_status_enum import PdmConfigAcmeStatusEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount(BaseModel):
    """
    ACME Account data. This is the part of the account returned from and possibly sent to the ACME provider. Some fields may be uptdated by the user via a request to the account location, others may not be changed.
    """ # noqa: E501

    contact: List[StrictStr] = Field(description="The account's contact info.  This usually contains a `\"mailto:<email address>\"` entry but may also contain some other data if the server accepts it.")

    external_account_binding: Optional[ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccountExternalAccountBinding] = Field(default=None, alias="externalAccountBinding")

    only_return_existing: StrictBool = Field(description="This is only used by the client when querying an account.", alias="onlyReturnExisting")

    orders: Optional[StrictStr] = Field(default=None, description="URLs to currently pending orders.")

    status: PdmConfigAcmeStatusEnum = Field(description="Status of an ACME account.")

    terms_of_service_agreed: Optional[StrictBool] = Field(default=None, description="Indicated whether the user agreed to the ACME provider's terms of service.", alias="termsOfServiceAgreed")

    __properties: ClassVar[List[str]] = ["contact", "externalAccountBinding", "onlyReturnExisting", "orders", "status", "termsOfServiceAgreed"]









    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of external_account_binding
        if self.external_account_binding:
            _dict['externalAccountBinding'] = self.external_account_binding.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccount from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "contact": obj.get("contact"),
            "externalAccountBinding": ConfigAcmeGetConfigAcmeAccountByNameResponseDataAccountExternalAccountBinding.from_dict(obj["externalAccountBinding"]) if obj.get("externalAccountBinding") is not None else None,
            "onlyReturnExisting": obj.get("onlyReturnExisting"),
            "orders": obj.get("orders"),
            "status": obj.get("status"),
            "termsOfServiceAgreed": obj.get("termsOfServiceAgreed")
        })
        return _obj


