# coding: utf-8

"""
    Proxmox Datacenter Manager API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from clientapi_pdm.models.pdm_delete_enum import PdmDeleteEnum
from clientapi_pdm.models.pdm_mode_enum import PdmModeEnum
from clientapi_pdm.models.pdm_sync_attributes_field import PdmSyncAttributesField
from clientapi_pdm.models.pdm_sync_defaults_options_field import PdmSyncDefaultsOptionsField
from clientapi_pdm.models.pdm_user_classes_field import PdmUserClassesField
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ConfigAccessUpdateAdRequest(BaseModel):
    """
    ConfigAccessUpdateAdRequest
    """ # noqa: E501

    base_dn: Optional[StrictStr] = Field(default=None, description="LDAP Domain", alias="base-dn")

    bind_dn: Optional[StrictStr] = Field(default=None, description="LDAP Domain", alias="bind-dn")

    capath: Optional[StrictStr] = Field(default=None, description="CA certificate to use for the server. The path can point to either a file, or a directory. If it points to a file, the PEM-formatted X.509 certificate stored at the path will be added as a trusted certificate. If the path points to a directory, the directory replaces the system's default certificate store at `/etc/ssl/certs` - Every file in the directory will be loaded as a trusted certificate.")

    comment: Optional[Annotated[str, Field(strict=True, max_length=128)]] = Field(default=None, description="Comment.")

    default: Optional[StrictBool] = Field(default=False, description="True if you want this to be the default realm selected on login.")

    delete: Optional[List[PdmDeleteEnum]] = Field(default=None, description="List of properties to delete.")

    digest: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Prevent changes if current configuration file has different SHA256 digest. This can be used to prevent concurrent modifications.")

    filter: Optional[StrictStr] = Field(default=None, description="Custom LDAP search filter for user sync")

    mode: Optional[PdmModeEnum] = Field(default=None, description="LDAP connection type")

    password: Optional[StrictStr] = Field(default=None, description="AD bind password")

    port: Optional[Annotated[int, Field(le=65535, strict=True, ge=0)]] = Field(default=None, description="AD server Port")

    server1: Optional[StrictStr] = Field(default=None, description="AD server address")

    server2: Optional[StrictStr] = Field(default=None, description="Fallback AD server address")

    sync_attributes: Optional[PdmSyncAttributesField] = Field(default=None, description="Comma-separated list of key=value pairs for specifying which LDAP attributes map to which peat user field. For example, to map the LDAP attribute ``mail`` to peat's ``email``, write ``email=mail``.", alias="sync-attributes")

    sync_defaults_options: Optional[PdmSyncDefaultsOptionsField] = Field(default=None, description="sync defaults options", alias="sync-defaults-options")

    user_classes: Optional[PdmUserClassesField] = Field(default=None, description="Comma-separated list of allowed objectClass values for user synchronization. For instance, if ``user-classes`` is set to ``person,user``, then user synchronization will consider all LDAP entities where ``objectClass: person`` `or` ``objectClass: user``.", alias="user-classes")

    verify: Optional[StrictBool] = Field(default=False, description="Verify server certificate")

    __properties: ClassVar[List[str]] = ["base-dn", "bind-dn", "capath", "comment", "default", "delete", "digest", "filter", "mode", "password", "port", "server1", "server2", "sync-attributes", "sync-defaults-options", "user-classes", "verify"]





    @field_validator('comment')
    def comment_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[^\x00-\x1f\x7f]*$", value):
            raise ValueError(r"must validate the regular expression /^[^\x00-\x1f\x7f]*$/")
        return value




    @field_validator('digest')
    def digest_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[a-f0-9]{64}$", value):
            raise ValueError(r"must validate the regular expression /^[a-f0-9]{64}$/")
        return value













    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConfigAccessUpdateAdRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            # `exclude_unset` keeps schema defaults out of the wire payload
            # when the user constructed the model directly (e.g.
            # `Req(vmid=100)` would otherwise pull in
            # `cores=1, cpulimit=0, …` from the spec defaults and PVE
            # rejects the request with 400 because it never set those).
            # `exclude_none` keeps None values out of the wire payload —
            # both for direct construction (None means "unset") and for
            # the from_dict path (where unspecified obj keys become
            # `obj.get("k") == None` but show up in `model_fields_set`).
            exclude_unset=True,
            exclude_none=True,
        )
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        # override the default output from pydantic by calling `to_dict()` of sync_attributes
        if self.sync_attributes:
            _dict['sync-attributes'] = self.sync_attributes.to_dict()
        
        # override the default output from pydantic by calling `to_dict()` of sync_defaults_options
        if self.sync_defaults_options:
            _dict['sync-defaults-options'] = self.sync_defaults_options.to_dict()
        
        # override the default output from pydantic by calling `to_dict()` of user_classes
        if self.user_classes:
            _dict['user-classes'] = self.user_classes.to_dict()
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConfigAccessUpdateAdRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "base-dn": obj.get("base-dn"),
            "bind-dn": obj.get("bind-dn"),
            "capath": obj.get("capath"),
            "comment": obj.get("comment"),
            "default": obj.get("default") if obj.get("default") is not None else False,
            "delete": obj.get("delete"),
            "digest": obj.get("digest"),
            "filter": obj.get("filter"),
            "mode": obj.get("mode"),
            "password": obj.get("password"),
            "port": obj.get("port"),
            "server1": obj.get("server1"),
            "server2": obj.get("server2"),
            "sync-attributes": PdmSyncAttributesField.from_dict(obj["sync-attributes"]) if obj.get("sync-attributes") is not None else None,
            "sync-defaults-options": PdmSyncDefaultsOptionsField.from_dict(obj["sync-defaults-options"]) if obj.get("sync-defaults-options") is not None else None,
            "user-classes": PdmUserClassesField.from_dict(obj["user-classes"]) if obj.get("user-classes") is not None else None,
            "verify": obj.get("verify") if obj.get("verify") is not None else False
        })
        return _obj


