# coding: utf-8

"""
    Proxmox Datacenter Manager API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from clientapi_pdm.models.pdm_acme_field import PdmAcmeField
from clientapi_pdm.models.pdm_acmedomain_field import PdmAcmedomainField
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ConfigCertificateGetCertificateResponseData(BaseModel):
    """
    ConfigCertificateGetCertificateResponseData
    """ # noqa: E501

    acme: Optional[PdmAcmeField] = Field(default=None, description="The acme account to use.")

    acmedomain0: Optional[PdmAcmedomainField] = Field(default=None, description="ACME domain configuration string")

    acmedomain1: Optional[PdmAcmedomainField] = Field(default=None, description="ACME domain configuration string")

    acmedomain2: Optional[PdmAcmedomainField] = Field(default=None, description="ACME domain configuration string")

    acmedomain3: Optional[PdmAcmedomainField] = Field(default=None, description="ACME domain configuration string")

    acmedomain4: Optional[PdmAcmedomainField] = Field(default=None, description="ACME domain configuration string")

    __properties: ClassVar[List[str]] = ["acme", "acmedomain0", "acmedomain1", "acmedomain2", "acmedomain3", "acmedomain4"]









    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConfigCertificateGetCertificateResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of acme
        if self.acme:
            _dict['acme'] = self.acme.to_dict()
        # override the default output from pydantic by calling `to_dict()` of acmedomain0
        if self.acmedomain0:
            _dict['acmedomain0'] = self.acmedomain0.to_dict()
        # override the default output from pydantic by calling `to_dict()` of acmedomain1
        if self.acmedomain1:
            _dict['acmedomain1'] = self.acmedomain1.to_dict()
        # override the default output from pydantic by calling `to_dict()` of acmedomain2
        if self.acmedomain2:
            _dict['acmedomain2'] = self.acmedomain2.to_dict()
        # override the default output from pydantic by calling `to_dict()` of acmedomain3
        if self.acmedomain3:
            _dict['acmedomain3'] = self.acmedomain3.to_dict()
        # override the default output from pydantic by calling `to_dict()` of acmedomain4
        if self.acmedomain4:
            _dict['acmedomain4'] = self.acmedomain4.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConfigCertificateGetCertificateResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "acme": PdmAcmeField.from_dict(obj["acme"]) if obj.get("acme") is not None else None,
            "acmedomain0": PdmAcmedomainField.from_dict(obj["acmedomain0"]) if obj.get("acmedomain0") is not None else None,
            "acmedomain1": PdmAcmedomainField.from_dict(obj["acmedomain1"]) if obj.get("acmedomain1") is not None else None,
            "acmedomain2": PdmAcmedomainField.from_dict(obj["acmedomain2"]) if obj.get("acmedomain2") is not None else None,
            "acmedomain3": PdmAcmedomainField.from_dict(obj["acmedomain3"]) if obj.get("acmedomain3") is not None else None,
            "acmedomain4": PdmAcmedomainField.from_dict(obj["acmedomain4"]) if obj.get("acmedomain4") is not None else None
        })
        return _obj


