# coding: utf-8

"""
    Proxmox Datacenter Manager API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class NodesTasksGetStatusResponseData(BaseModel):
    """
    NodesTasksGetStatusResponseData
    """ # noqa: E501

    exitstatus: Optional[StrictStr] = Field(default=None, description="'OK', 'Error: <msg>', or 'unknown'.")

    id: Optional[StrictStr] = Field(default=None, description="Worker ID (arbitrary ASCII string)")

    node: Annotated[str, Field(strict=True)] = Field(description="Node name (or 'localhost')")

    pid: int = Field(description="The Unix PID.")

    pstart: int = Field(description="The Unix process start time from `/proc/pid/stat`")

    starttime: int = Field(description="The task start time (Epoch)")

    status: StrictStr = Field(description="'running' or 'stopped'")

    tokenid: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="The token ID part of an API token authentication id.  This alone does NOT uniquely identify the API token - use a full `Authid` for such use cases.")

    type: StrictStr = Field(description="Worker type (arbitrary ASCII string)")

    upid: Annotated[str, Field(min_length=36, strict=True)] = Field(description="Unique Process/Task Identifier")

    user: Annotated[str, Field(min_length=3, strict=True, max_length=64)] = Field(description="User ID")

    __properties: ClassVar[List[str]] = ["exitstatus", "id", "node", "pid", "pstart", "starttime", "status", "tokenid", "type", "upid", "user"]




    @field_validator('node')
    def node_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^(?:[a-zA-Z0-9](?:[a-zA-Z0-9\-]*[a-zA-Z0-9])?)$", value):
            raise ValueError(r"must validate the regular expression /^(?:[a-zA-Z0-9](?:[a-zA-Z0-9\-]*[a-zA-Z0-9])?)$/")
        return value






    @field_validator('tokenid')
    def tokenid_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^(?:[A-Za-z0-9_][A-Za-z0-9._\-]*)$", value):
            raise ValueError(r"must validate the regular expression /^(?:[A-Za-z0-9_][A-Za-z0-9._\-]*)$/")
        return value




    @field_validator('user')
    def user_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^(?:[^\s:/[:cntrl:]]+)@(?:[A-Za-z0-9_][A-Za-z0-9._\-]*)$", value):
            raise ValueError(r"must validate the regular expression /^(?:[^\s:/[:cntrl:]]+)@(?:[A-Za-z0-9_][A-Za-z0-9._\-]*)$/")
        return value



    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NodesTasksGetStatusResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            # `exclude_unset` keeps schema defaults out of the wire payload
            # when the user constructed the model directly (e.g.
            # `Req(vmid=100)` would otherwise pull in
            # `cores=1, cpulimit=0, …` from the spec defaults and PVE
            # rejects the request with 400 because it never set those).
            # `exclude_none` keeps None values out of the wire payload —
            # both for direct construction (None means "unset") and for
            # the from_dict path (where unspecified obj keys become
            # `obj.get("k") == None` but show up in `model_fields_set`).
            exclude_unset=True,
            exclude_none=True,
        )
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NodesTasksGetStatusResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "exitstatus": obj.get("exitstatus"),
            "id": obj.get("id"),
            "node": obj.get("node"),
            "pid": obj.get("pid"),
            "pstart": obj.get("pstart"),
            "starttime": obj.get("starttime"),
            "status": obj.get("status"),
            "tokenid": obj.get("tokenid"),
            "type": obj.get("type"),
            "upid": obj.get("upid"),
            "user": obj.get("user")
        })
        return _obj


