# coding: utf-8

"""
    Proxmox Datacenter Manager API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from clientapi_pdm.models.pdm_maintenance_mode_field import PdmMaintenanceModeField
from clientapi_pdm.models.pdm_notify_field import PdmNotifyField
from clientapi_pdm.models.pdm_pbs_remotes_notification_mode_enum import PdmPbsRemotesNotificationModeEnum
from clientapi_pdm.models.pdm_tuning_field import PdmTuningField
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PbsRemotesGetDatastoreResponseDataInner(BaseModel):
    """
    PbsRemotesGetDatastoreResponseDataInner
    """ # noqa: E501

    backend: Optional[StrictStr] = Field(default=None, description="Datastore backend config")

    backing_device: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="The UUID of the filesystem partition for removable datastores.", alias="backing-device")

    comment: Optional[Annotated[str, Field(strict=True, max_length=128)]] = Field(default=None, description="Comment.")

    gc_schedule: Optional[StrictStr] = Field(default=None, description="Run garbage collection job at specified schedule.", alias="gc-schedule")

    keep_daily: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Number of daily backups to keep.", alias="keep-daily")

    keep_hourly: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Number of hourly backups to keep.", alias="keep-hourly")

    keep_last: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Number of backups to keep.", alias="keep-last")

    keep_monthly: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Number of monthly backups to keep.", alias="keep-monthly")

    keep_weekly: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Number of weekly backups to keep.", alias="keep-weekly")

    keep_yearly: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Number of yearly backups to keep.", alias="keep-yearly")

    maintenance_mode: Optional[PdmMaintenanceModeField] = Field(default=None, description="Maintenance mode, type is either 'offline' or 'read-only', message should be enclosed in \"", alias="maintenance-mode")

    name: Annotated[str, Field(min_length=3, strict=True, max_length=32)] = Field(description="Datastore name.")

    notification_mode: Optional[PdmPbsRemotesNotificationModeEnum] = Field(default=None, description="Configure how notifications for this datastore should be sent. `legacy-sendmail` sends email notifications to the user configured in `notify-user` via the system's `sendmail` executable. `notification-system` emits matchable notification events to the notification system.", alias="notification-mode")

    notify: Optional[PdmNotifyField] = Field(default=None, description="Datastore notification setting, enum can be one of 'always', 'never', or 'error'.")

    notify_user: Optional[Annotated[str, Field(min_length=3, strict=True, max_length=64)]] = Field(default=None, description="User ID", alias="notify-user")

    path: Annotated[str, Field(min_length=1, strict=True, max_length=4096)] = Field(description="Either the absolute path to the datastore directory, or a relative on-device path for removable datastores.")

    prune_schedule: Optional[StrictStr] = Field(default=None, description="Run prune job at specified schedule.", alias="prune-schedule")

    tuning: Optional[PdmTuningField] = Field(default=None, description="Datastore tuning options")

    verify_new: Optional[StrictBool] = Field(default=None, description="If enabled, all new backups will be verified right after completion.", alias="verify-new")

    __properties: ClassVar[List[str]] = ["backend", "backing-device", "comment", "gc-schedule", "keep-daily", "keep-hourly", "keep-last", "keep-monthly", "keep-weekly", "keep-yearly", "maintenance-mode", "name", "notification-mode", "notify", "notify-user", "path", "prune-schedule", "tuning", "verify-new"]



    @field_validator('backing_device')
    def backing_device_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}$", value):
            raise ValueError(r"must validate the regular expression /^[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}$/")
        return value


    @field_validator('comment')
    def comment_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[[:^cntrl:]]*$", value):
            raise ValueError(r"must validate the regular expression /^[[:^cntrl:]]*$/")
        return value










    @field_validator('name')
    def name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^(?:[A-Za-z0-9_][A-Za-z0-9._\-]*)$", value):
            raise ValueError(r"must validate the regular expression /^(?:[A-Za-z0-9_][A-Za-z0-9._\-]*)$/")
        return value




    @field_validator('notify_user')
    def notify_user_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^(?:[^\s:/[:cntrl:]]+)@(?:[A-Za-z0-9_][A-Za-z0-9._\-]*)$", value):
            raise ValueError(r"must validate the regular expression /^(?:[^\s:/[:cntrl:]]+)@(?:[A-Za-z0-9_][A-Za-z0-9._\-]*)$/")
        return value







    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PbsRemotesGetDatastoreResponseDataInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of maintenance_mode
        if self.maintenance_mode:
            _dict['maintenance-mode'] = self.maintenance_mode.to_dict()
        # override the default output from pydantic by calling `to_dict()` of notify
        if self.notify:
            _dict['notify'] = self.notify.to_dict()
        # override the default output from pydantic by calling `to_dict()` of tuning
        if self.tuning:
            _dict['tuning'] = self.tuning.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PbsRemotesGetDatastoreResponseDataInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "backend": obj.get("backend"),
            "backing-device": obj.get("backing-device"),
            "comment": obj.get("comment"),
            "gc-schedule": obj.get("gc-schedule"),
            "keep-daily": obj.get("keep-daily"),
            "keep-hourly": obj.get("keep-hourly"),
            "keep-last": obj.get("keep-last"),
            "keep-monthly": obj.get("keep-monthly"),
            "keep-weekly": obj.get("keep-weekly"),
            "keep-yearly": obj.get("keep-yearly"),
            "maintenance-mode": PdmMaintenanceModeField.from_dict(obj["maintenance-mode"]) if obj.get("maintenance-mode") is not None else None,
            "name": obj.get("name"),
            "notification-mode": obj.get("notification-mode"),
            "notify": PdmNotifyField.from_dict(obj["notify"]) if obj.get("notify") is not None else None,
            "notify-user": obj.get("notify-user"),
            "path": obj.get("path"),
            "prune-schedule": obj.get("prune-schedule"),
            "tuning": PdmTuningField.from_dict(obj["tuning"]) if obj.get("tuning") is not None else None,
            "verify-new": obj.get("verify-new")
        })
        return _obj


