# coding: utf-8

"""
    Proxmox Datacenter Manager API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PdmVlanProtocolEnum(str, Enum):
    """
    PdmVlanProtocolEnum
    """

    """
    allowed enum values
    """
    ENUM_802_DOT_1AD = '802.1ad'
    ENUM_802_DOT_1Q = '802.1q'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PdmVlanProtocolEnum from a JSON string"""
        return cls(json.loads(json_str))


