# coding: utf-8

"""
    Proxmox Datacenter Manager API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PdmBondModeEnum(str, Enum):
    """
    PdmBondModeEnum
    """

    """
    allowed enum values
    """
    BALANCE_MINUS_RR = 'balance-rr'
    ACTIVE_MINUS_BACKUP = 'active-backup'
    BALANCE_MINUS_XOR = 'balance-xor'
    BROADCAST = 'broadcast'
    ENUM_802_DOT_3AD = '802.3ad'
    BALANCE_MINUS_TLB = 'balance-tlb'
    BALANCE_MINUS_ALB = 'balance-alb'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PdmBondModeEnum from a JSON string"""
        return cls(json.loads(json_str))


