# coding: utf-8

"""
    Proxmox Datacenter Manager API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PdmAccessAclUgidTypeEnum(str, Enum):
    """
    PdmAccessAclUgidTypeEnum
    """

    """
    allowed enum values
    """
    USER = 'user'
    GROUP = 'group'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PdmAccessAclUgidTypeEnum from a JSON string"""
        return cls(json.loads(json_str))


