# coding: utf-8

"""
    Proxmox Datacenter Manager API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PdmNodesAptHandleEnum(str, Enum):
    """
    PdmNodesAptHandleEnum
    """

    """
    allowed enum values
    """
    ENTERPRISE = 'enterprise'
    NO_MINUS_SUBSCRIPTION = 'no-subscription'
    TEST = 'test'
    CEPH_MINUS_SQUID_MINUS_ENTERPRISE = 'ceph-squid-enterprise'
    CEPH_MINUS_SQUID_MINUS_NO_MINUS_SUBSCRIPTION = 'ceph-squid-no-subscription'
    CEPH_MINUS_SQUID_MINUS_TEST = 'ceph-squid-test'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PdmNodesAptHandleEnum from a JSON string"""
        return cls(json.loads(json_str))


