# coding: utf-8

"""
    Proxmox Datacenter Manager API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from clientapi_pdm.models.pdm_content_field import PdmContentField
from clientapi_pdm.models.pve_remotes_get_storage_response_data_inner_formats import PveRemotesGetStorageResponseDataInnerFormats
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PveRemotesGetStorageResponseDataInner(BaseModel):
    """
    PveRemotesGetStorageResponseDataInner
    """ # noqa: E501

    active: Optional[StrictBool] = Field(default=False, description="Set when storage is accessible.")

    avail: Optional[StrictInt] = Field(default=None, description="Available storage space in bytes.")

    content: PdmContentField = Field(description="Allowed storage content types.")

    enabled: Optional[StrictBool] = Field(default=False, description="Set when storage is enabled (not disabled).")

    formats: Optional[PveRemotesGetStorageResponseDataInnerFormats] = None

    select_existing: Optional[StrictBool] = Field(default=False, description="Instead of creating new volumes, one must select one that is already existing. Only included if 'format' parameter is set.")

    shared: Optional[StrictBool] = Field(default=False, description="Shared flag from storage configuration.")

    storage: StrictStr = Field(description="The storage identifier.")

    total: Optional[StrictInt] = Field(default=None, description="Total storage space in bytes.")

    type: StrictStr = Field(description="Storage type.")

    used: Optional[StrictInt] = Field(default=None, description="Used storage space in bytes.")

    used_fraction: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Used fraction (used/total).")

    __properties: ClassVar[List[str]] = ["active", "avail", "content", "enabled", "formats", "select_existing", "shared", "storage", "total", "type", "used", "used_fraction"]















    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PveRemotesGetStorageResponseDataInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of content
        if self.content:
            _dict['content'] = self.content.to_dict()
        # override the default output from pydantic by calling `to_dict()` of formats
        if self.formats:
            _dict['formats'] = self.formats.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PveRemotesGetStorageResponseDataInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "active": obj.get("active") if obj.get("active") is not None else False,
            "avail": obj.get("avail"),
            "content": PdmContentField.from_dict(obj["content"]) if obj.get("content") is not None else None,
            "enabled": obj.get("enabled") if obj.get("enabled") is not None else False,
            "formats": PveRemotesGetStorageResponseDataInnerFormats.from_dict(obj["formats"]) if obj.get("formats") is not None else None,
            "select_existing": obj.get("select_existing") if obj.get("select_existing") is not None else False,
            "shared": obj.get("shared") if obj.get("shared") is not None else False,
            "storage": obj.get("storage"),
            "total": obj.get("total"),
            "type": obj.get("type"),
            "used": obj.get("used"),
            "used_fraction": obj.get("used_fraction")
        })
        return _obj


