# coding: utf-8

"""
    Proxmox Datacenter Manager API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from clientapi_pdm.models.pdm_log_ratelimit_field import PdmLogRatelimitField
from clientapi_pdm.models.pdm_policy_forward_enum import PdmPolicyForwardEnum
from clientapi_pdm.models.pdm_policy_in_enum import PdmPolicyInEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PveRemotesUpdateOptionsRequest(BaseModel):
    """
    PveRemotesUpdateOptionsRequest
    """ # noqa: E501

    delete: Optional[List[StrictStr]] = Field(default=None, description="A list of settings you want to delete.")

    digest: Optional[Annotated[str, Field(strict=True, max_length=64)]] = Field(default=None, description="Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications.")

    ebtables: Optional[StrictBool] = Field(default=True, description="Enable ebtables rules cluster wide.")

    enable: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=0, description="Enable or disable the firewall cluster wide.")

    log_ratelimit: Optional[PdmLogRatelimitField] = Field(default=None, description="Log ratelimiting settings")

    policy_forward: Optional[PdmPolicyForwardEnum] = Field(default=None, description="Firewall IO policies.")

    policy_in: Optional[PdmPolicyInEnum] = Field(default=None, description="Firewall IO policies.")

    policy_out: Optional[PdmPolicyInEnum] = Field(default=None, description="Firewall IO policies.")

    __properties: ClassVar[List[str]] = ["delete", "digest", "ebtables", "enable", "log_ratelimit", "policy_forward", "policy_in", "policy_out"]











    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PveRemotesUpdateOptionsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            # `exclude_unset` keeps schema defaults out of the wire payload
            # when the user constructed the model directly (e.g.
            # `Req(vmid=100)` would otherwise pull in
            # `cores=1, cpulimit=0, …` from the spec defaults and PVE
            # rejects the request with 400 because it never set those).
            # `exclude_none` keeps None values out of the wire payload —
            # both for direct construction (None means "unset") and for
            # the from_dict path (where unspecified obj keys become
            # `obj.get("k") == None` but show up in `model_fields_set`).
            exclude_unset=True,
            exclude_none=True,
        )
        
        
        
        
        
        # override the default output from pydantic by calling `to_dict()` of log_ratelimit
        if self.log_ratelimit:
            _dict['log_ratelimit'] = self.log_ratelimit.to_dict()
        
        
        
        
        
        
        
        
        
        
        
        
        
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PveRemotesUpdateOptionsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "delete": obj.get("delete"),
            "digest": obj.get("digest"),
            "ebtables": obj.get("ebtables") if obj.get("ebtables") is not None else True,
            "enable": obj.get("enable") if obj.get("enable") is not None else 0,
            "log_ratelimit": PdmLogRatelimitField.from_dict(obj["log_ratelimit"]) if obj.get("log_ratelimit") is not None else None,
            "policy_forward": obj.get("policy_forward"),
            "policy_in": obj.get("policy_in"),
            "policy_out": obj.get("policy_out")
        })
        return _obj


