# coding: utf-8

"""
    Proxmox Datacenter Manager API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from clientapi_pdm.models.pdm_remotes_remote_console_enum import PdmRemotesRemoteConsoleEnum
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class RemotesRemoteGetVersionResponseData(BaseModel):
    """
    RemotesRemoteGetVersionResponseData
    """ # noqa: E501

    console: Optional[PdmRemotesRemoteConsoleEnum] = Field(default=None, description="The default console viewer to use.")

    release: StrictStr = Field(description="The current Proxmox VE point release in `x.y` format.")

    repoid: StrictStr = Field(description="The short git revision from which this version was build.")

    version: StrictStr = Field(description="The full pve-manager package version of this node.")

    __properties: ClassVar[List[str]] = ["console", "release", "repoid", "version"]







    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RemotesRemoteGetVersionResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RemotesRemoteGetVersionResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "console": obj.get("console"),
            "release": obj.get("release"),
            "repoid": obj.get("repoid"),
            "version": obj.get("version")
        })
        return _obj


