# coding: utf-8

"""
    Proxmox Datacenter Manager API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from clientapi_pdm.models.resources_get_top_entities_response_data_guest_cpu_inner_rrd_data import ResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ResourcesGetTopEntitiesResponseDataGuestCpuInner(BaseModel):
    """
    ResourcesGetTopEntitiesResponseDataGuestCpuInner
    """ # noqa: E501

    remote: StrictStr = Field(description="The remote the resource is on")

    resource: Dict[str, Any]

    rrd_data: ResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData = Field(alias="rrd-data")

    __properties: ClassVar[List[str]] = ["remote", "resource", "rrd-data"]






    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ResourcesGetTopEntitiesResponseDataGuestCpuInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of rrd_data
        if self.rrd_data:
            _dict['rrd-data'] = self.rrd_data.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ResourcesGetTopEntitiesResponseDataGuestCpuInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "remote": obj.get("remote"),
            "resource": obj.get("resource"),
            "rrd-data": ResourcesGetTopEntitiesResponseDataGuestCpuInnerRrdData.from_dict(obj["rrd-data"]) if obj.get("rrd-data") is not None else None
        })
        return _obj


