# coding: utf-8

"""
    Proxmox Datacenter Manager API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from clientapi_pdm.models.sdn_zones_create_zones_request_remotes_inner import SdnZonesCreateZonesRequestRemotesInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SdnZonesCreateZonesRequest(BaseModel):
    """
    SdnZonesCreateZonesRequest
    """ # noqa: E501

    remotes: List[SdnZonesCreateZonesRequestRemotesInner] = Field(description="List of remotes with their controller where zone should get created.")

    vrf_vxlan: Optional[Annotated[int, Field(le=16777215, strict=True, ge=1)]] = Field(default=None, description="VXLAN VNI", alias="vrf-vxlan")

    zone: StrictStr = Field(description="The name for an SDN object (zone / vnet / fabric).")

    __properties: ClassVar[List[str]] = ["remotes", "vrf-vxlan", "zone"]






    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SdnZonesCreateZonesRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in remotes (list)
        _items = []
        if self.remotes:
            for _item_remotes in self.remotes:
                if _item_remotes:
                    _items.append(_item_remotes.to_dict())
            _dict['remotes'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SdnZonesCreateZonesRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "remotes": [SdnZonesCreateZonesRequestRemotesInner.from_dict(_item) for _item in obj["remotes"]] if obj.get("remotes") is not None else None,
            "vrf-vxlan": obj.get("vrf-vxlan"),
            "zone": obj.get("zone")
        })
        return _obj


