# coding: utf-8

"""
    Proxmox Datacenter Manager API

    Generated from apidoc.js. NOT an official Proxmox specification. See https://pdm.proxmox.com/docs/api-viewer/ for the upstream documentation.

    The version of the OpenAPI document: 9.x
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SdnGetControllersResponseDataInnerPending(BaseModel):
    """
    Changes that have not yet been applied to the running configuration.
    """ # noqa: E501

    asn: Optional[Annotated[int, Field(le=4294967295, strict=True, ge=0)]] = Field(default=None, description="The local ASN of the controller. BGP & EVPN only.")

    bgp_multipath_as_relax: Optional[StrictBool] = Field(default=False, description="Consider different AS paths of equal length for multipath computation. BGP only.", alias="bgp-multipath-as-relax")

    ebgp: Optional[StrictBool] = Field(default=False, description="Enable eBGP (remote-as external). BGP only.")

    ebgp_multihop: Optional[StrictInt] = Field(default=None, description="Set maximum amount of hops for eBGP peers. Needs ebgp set to 1. BGP only.", alias="ebgp-multihop")

    isis_domain: Optional[StrictStr] = Field(default=None, description="Name of the IS-IS domain. IS-IS only.", alias="isis-domain")

    isis_ifaces: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Comma-separated list of interfaces where IS-IS should be active. IS-IS only.", alias="isis-ifaces")

    isis_net: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Network Entity title for this node in the IS-IS network. IS-IS only.", alias="isis-net")

    loopback: Optional[StrictStr] = Field(default=None, description="Name of the loopback/dummy interface that provides the Router-IP. BGP only.")

    node: Optional[StrictStr] = Field(default=None, description="Node(s) where this controller is active.")

    peers: Optional[StrictStr] = Field(default=None, description="Comma-separated list of the peers IP addresses.")

    __properties: ClassVar[List[str]] = ["asn", "bgp-multipath-as-relax", "ebgp", "ebgp-multihop", "isis-domain", "isis-ifaces", "isis-net", "loopback", "node", "peers"]







    @field_validator('isis_ifaces')
    def isis_ifaces_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[a-zA-Z][a-zA-Z0-9_]{1,20}([:\.]\d+)?$", value):
            raise ValueError(r"must validate the regular expression /^[a-zA-Z][a-zA-Z0-9_]{1,20}([:\.]\d+)?$/")
        return value


    @field_validator('isis_net')
    def isis_net_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[a-fA-F0-9]{2}(\.[a-fA-F0-9]{4}){3,9}\.[a-fA-F0-9]{2}$", value):
            raise ValueError(r"must validate the regular expression /^[a-fA-F0-9]{2}(\.[a-fA-F0-9]{4}){3,9}\.[a-fA-F0-9]{2}$/")
        return value






    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SdnGetControllersResponseDataInnerPending from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            # `exclude_unset` keeps schema defaults out of the wire payload
            # when the user constructed the model directly (e.g.
            # `Req(vmid=100)` would otherwise pull in
            # `cores=1, cpulimit=0, …` from the spec defaults and PVE
            # rejects the request with 400 because it never set those).
            # `exclude_none` keeps None values out of the wire payload —
            # both for direct construction (None means "unset") and for
            # the from_dict path (where unspecified obj keys become
            # `obj.get("k") == None` but show up in `model_fields_set`).
            exclude_unset=True,
            exclude_none=True,
        )
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SdnGetControllersResponseDataInnerPending from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "asn": obj.get("asn"),
            "bgp-multipath-as-relax": obj.get("bgp-multipath-as-relax") if obj.get("bgp-multipath-as-relax") is not None else False,
            "ebgp": obj.get("ebgp") if obj.get("ebgp") is not None else False,
            "ebgp-multihop": obj.get("ebgp-multihop"),
            "isis-domain": obj.get("isis-domain"),
            "isis-ifaces": obj.get("isis-ifaces"),
            "isis-net": obj.get("isis-net"),
            "loopback": obj.get("loopback"),
            "node": obj.get("node"),
            "peers": obj.get("peers")
        })
        return _obj


